server:
  port: 8090
  servlet:
    context-path: /auth
management:
  endpoint:
    restart:
      enabled: true
spring:
  application:
    name: authorization
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    # 172.17.0.1(Docker) ou db-service(k8s) si le service tourne dans un container localhost sinon
    host: localhost
    port: 3307
    url: jdbc:mariadb://${spring.datasource.host}:${spring.datasource.port}/bank
    username: spring
    password: spring
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
    validationQuery:
      SELECT 1
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

security:
  client: client
  authorizedGrantTypes:
    - authorization_code
    - password
  scopes: user_info
  redirectUris:
    - http://127.0.0.1:8200/login
    - http://localhost:8200/login
    - http://172.22.0.1:8200/login
    - http://192.168.99.100:30200/login
    - http://localhost:3000
  password: password
